/**:
  ros__parameters:
    shelves:
      TAG-A1-001:
        x: 0.4778
        y: -0.1872
        yaw: -0.1499
      TAG-A1-002:
        x: -0.5233
        y: -0.2373
        yaw: 0.0842
      TAG-B1-001:
        x: -1.0757
        y: 1.6363
        yaw: 3.0595
      TAG-B1-002:
        x: 0.1601
        y: 1.7781
        yaw: -3.0558
