/**:
  ros__parameters:
    topics:
      # 1순위: 수동 조작 (UI / 키보드) - 200 (최고 우선순위)
      teleop:
        topic: "/cmd_vel_teleop"
        timeout: 1.0 # 허용 오차 확대 (0.5 -> 1.0)
        priority: 200
      # 2순위: 장애물 관리 (사용자 노드) - 100
      obstacle:
        topic: "/cmd_vel_obstacle"
        timeout: 1.0 # 촘촘한 정지 명령 유지를 위해 1.0초 확보
        priority: 100
      # 3순위: 기본 순찰 (내비게이션) - 5
      navigation:
        topic: "/cmd_vel_nav"
        timeout: 1.0
        priority: 5
